name: Build CatalogoCards

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Rush
        run: |
          curl https://raw.githubusercontent.com/shreyashsaitwal/rush-cli/main/scripts/install/install.sh -fsSL | sh
          echo "$HOME/.rush/bin" >> $GITHUB_PATH

      - name: Compilar extensão
        run: rush build

      - name: Guardar AIX
        uses: actions/upload-artifact@v4
        with:
          name: CatalogoCards-AIX
          path: out/*.aix
