name: Build CatalogoCards

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'

      - name: Dar permissão ao Ant
        run: chmod +x ./ant

      - name: Compilar extensão
        run: ./ant

      - name: Procurar arquivo AIX
        run: |
          echo "Arquivos AIX encontrados:"
          find . -type f -name "*.aix" -print

      - name: Guardar extensão
        uses: actions/upload-artifact@v4
        with:
          name: CatalogoCards
          path: "**/*.aix"
          if-no-files-found: error
